[deps]
Blink = "ad839575-38b3-5650-b840-f874b8c74a25"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
MeshCatMechanisms = "6ad125db-dd91-5488-b820-c1df6aab299d"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
RigidBodyDynamics = "366cf18f-59d5-5db9-a4de-86a9f6786172"
RigidBodySim = "e61f16d8-a6b7-5689-8d03-627c2b27ebce"

